default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: developer
  password: developer
  host:     localhost

development:
  <<: *default
  database: volt-test_development

test:
  <<: *default
  database: volt-test_test

production:
  <<: *default
  database: volt-test_production
  username: volt-test
  password: <%= ENV['VOLT-TEST_DATABASE_PASSWORD'] %>
