# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8e24ef3701e1fad4bfe22f6c29893d6033d60c3e41be400a2409fd05ebfe7f6c40c6b94293d932edc02a79f6346d4690cc908ab1ca4ab89e6495597b6c75a6b1

test:
  secret_key_base: 1da1a882a376081cfae9857dc3a58ceef1018330f86fe6372a90eab8d66d540d2fd7d0faad2880a434fa78034d5508cc63d69420e71f4f03e253748184986285

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
